/* =========================================
   DAKTELA ROI CALCULATOR - COMPLETE LOGIC
   ========================================= */

// 1. DATA & TRANSLATIONS
window.translations = window.translations || {};

// EN - English
window.translations.en = {
    "header": { "title": "Daktela ROI-culator", "subtitle": "Find out how much you can save by integrating communication channels and automating with AI" },
    "form": { "operators": "Number of customer support operators", "channels": { "title": "Communication channels and monthly query count", "phone": "Phone", "email": "E-mail", "chat": "Chat", "sms": "SMS", "messenger": "Socials", "phonePlaceholder": "Number of calls/month", "emailPlaceholder": "Number of emails/month", "chatPlaceholder": "Number of chats/month", "smsPlaceholder": "Number of SMS/month", "messengerPlaceholder": "Number of messages/month" }, "avgTime": "Average time to resolve a query (minutes)", "hourlyWage": "Average hourly wage of operator", "currency": "Currency", "industry": { "label": "Industry selection", "placeholder": "Select industry", "ecommerce": "E-commerce", "logistics": "Logistics & Transportation", "finance": "Financial Services & Insurance", "manufacturing": "Manufacturing", "travel": "Travel & Tourism", "telecom": "Telecommunications & Call Centers", "automotive": "Automotive", "it": "IT", "energy": "Energy", "healthcare": "Healthcare", "other": "Other" }, "repeatQueries": "Ratio of repeating queries:", "buttons": { "calculate": "Calculate Savings", "reset": "Reset" } },
    "results": { "title": "Your Potential Savings", "totalSavings": "Potential annual saving", "chartTitle": "Savings Visualization", "channelBreakdown": "Savings Breakdown by Channel", "automation": "automation", "downloadPdf": "Download PDF Report" },
    "pdf": { "inputParameters": "Input Parameters", "numberOfOperators": "Number of operators", "averageResolutionTime": "Average resolution time", "hourlyWage": "Hourly wage", "industry": "Industry", "repeatingQueriesRatio": "Repeating queries ratio", "activeChannels": "Active channels", "minutes": "minutes", "generatedBy": "Generated by Daktela ROI-culator", "reportGeneratedOn": "Report generated on", "disclaimer": "All values shown represent potential estimated savings based on provided input data and industry standards. Actual results may vary case by case and always depend on specific implementation conditions." },
    "industries": {
        "ecommerce": { "name": "E-commerce", "insight": "By integrating all communication channels into one platform, you can typically achieve up to {integration} operational savings. AI automation can usually handle up to {ai} of your customer queries automatically. Together, these solutions typically deliver up to {combined} total potential savings for your e-commerce operations." },
        "logistics": { "name": "Logistics & Transportation", "insight": "Channel integration typically provides up to {integration} operational cost reduction through unified tracking and communication. AI automation usually handles up to {ai} of shipment and delivery inquiries without human intervention. Combined, you can typically achieve up to {combined} total operational efficiency improvement." },
        "finance": { "name": "Financial Services & Insurance", "insight": "Integrating communication channels typically saves up to {integration} in operational costs while maintaining security compliance. AI can usually automate up to {ai} of balance, payment, and product inquiries. Together, these typically deliver up to {combined} total operational savings for financial services." },
        "manufacturing": { "name": "Manufacturing", "insight": "Channel integration typically reduces operational costs by up to {integration} through streamlined order management. AI automation usually handles up to {ai} of availability, specifications, and delivery queries. Combined implementation typically achieves up to {combined} total operational efficiency gains." },
        "travel": { "name": "Travel & Tourism", "insight": "Unified communication channels typically provide up to {integration} cost savings and faster booking processing. AI can usually automate up to {ai} of reservation and destination inquiries. Together, you can typically achieve up to {combined} total operational improvement in travel services." },
        "telecom": { "name": "Telecommunications & Call Centers", "insight": "Channel integration typically delivers up to {integration} operational savings with unified customer views. AI automation usually handles up to {ai} of technical, activation, and billing queries. Combined solutions typically provide up to {combined} total potential for operational excellence." },
        "automotive": { "name": "Automotive", "insight": "Integrating communication channels typically reduces service costs by up to {integration} while improving customer experience. AI can usually automate up to {ai} of parts, service, and vehicle information queries. Together, these typically achieve up to {combined} total operational efficiency improvement." },
        "it": { "name": "IT", "insight": "Channel integration typically provides up to {integration} operational cost reduction through unified IT support platforms. AI automation can usually handle up to {ai} of technical support and system inquiries automatically. Combined, these solutions typically deliver up to {combined} total potential for IT operational efficiency improvements." },
        "energy": { "name": "Energy", "insight": "Integrating communication channels typically saves up to {integration} in operational costs while maintaining regulatory compliance. AI can usually automate up to {ai} of billing, usage, and service inquiries. Together, these typically deliver up to {combined} total operational savings for energy providers." },
        "healthcare": { "name": "Healthcare", "insight": "Channel integration typically provides up to {integration} operational cost reduction while ensuring patient privacy compliance. AI automation can usually handle up to {ai} of appointment, billing, and general health inquiries. Combined solutions typically deliver up to {combined} total potential for healthcare operational improvements." },
        "other": { "name": "Other", "insight": "Channel integration typically provides up to {integration} operational cost reduction across various industries. AI automation can usually handle up to {ai} of common customer queries automatically. Combined, these solutions typically deliver up to {combined} total potential for operational efficiency improvements." }
    },
    "caseStudies": { "ecommerce": null, "logistics": null, "finance": null, "manufacturing": null, "travel": null, "telecom": null, "automotive": null, "it": null, "energy": null, "healthcare": null, "other": null },
    "caseStudyText": { "prefix": "See how", "suffix": "uses Daktela!" },
    "validation": { "channelsRequired": "Please select at least one communication channel." },
    "chart": { "savingsLabel": "Annual Savings (CZK)", "hoursLabel": "Hours Saved Annually", "savingsAxis": "Savings (CZK)", "hoursAxis": "Hours", "integrationLabel": "Channel Integration", "aiAutomationLabel": "AI Automation", "potentialSavingsTitle": "Potential Savings by Segment - Channel Integration vs. AI", "percentageAxis": "Potential Savings (%)", "savingsBreakdownTitle": "Potential Savings Breakdown", "integrationOnly": "Channels\nintegration", "aiOnly": "AI Automation", "bothCombined": "Combined" },
    "leadModal": { "title": "Get your personalized report", "subtitle": "Enter your details to unlock your savings results.", "firstName": "First name", "lastName": "Last name", "company": "Company", "email": "Work email", "submit": "Show my results", "sending": "Sending...", "validation": { "required": "Please fill in all fields.", "email": "Please enter a valid email address." } }
};

// CS - Czech
window.translations.cs = {
    "header": { "title": "Daktela ROI-culator", "subtitle": "Zjistěte, kolik můžete ušetřit integrací komunikačních kanálů a automatizací pomocí AI" },
    "form": { "operators": "Počet operátorů v zákaznické podpoře", "channels": { "title": "Komunikační kanály a počet dotazů měsíčně", "phone": "Telefon", "email": "E-mail", "chat": "Chat", "sms": "SMS", "messenger": "Sociální sítě", "phonePlaceholder": "Počet hovorů/měsíc", "emailPlaceholder": "Počet e-mailů/měsíc", "chatPlaceholder": "Počet chatů/měsíc", "smsPlaceholder": "Počet SMS/měsíc", "messengerPlaceholder": "Počet zpráv/měsíc" }, "avgTime": "Průměrný čas na vyřešení dotazu (minuty)", "hourlyWage": "Průměrná hodinová mzda operátora", "currency": "Měna", "industry": { "label": "Výběr odvětví", "placeholder": "Vyberte odvětví", "ecommerce": "E-commerce", "logistics": "Logistika & doprava", "finance": "Finanční služby & pojištění", "manufacturing": "Výroba", "travel": "Cestovní ruch & agentury", "telecom": "Telekomunikace & call centra", "automotive": "Automotive", "it": "IT", "energy": "Energetika", "healthcare": "Zdravotnictví", "other": "Ostatní" }, "repeatQueries": "Poměr opakujících se dotazů:", "buttons": { "calculate": "Spočítat úspory", "reset": "Resetovat" } },
    "results": { "title": "Vaše potenciální úspory", "totalSavings": "Potenciální roční úspora", "chartTitle": "Vizualizace úspor", "channelBreakdown": "Rozpad úspor podle kanálů", "automation": "automatizace", "downloadPdf": "Stáhnout PDF zprávu" },
    "pdf": { "inputParameters": "Vstupní parametry", "numberOfOperators": "Počet operátorů", "averageResolutionTime": "Průměrná doba řešení", "hourlyWage": "Hodinová mzda", "industry": "Odvětví", "repeatingQueriesRatio": "Poměr opakujících se dotazů", "activeChannels": "Aktivní kanály", "minutes": "minut", "generatedBy": "Vygenerováno pomocí Daktela ROI-calculator", "reportGeneratedOn": "Zpráva vygenerována", "disclaimer": "Všechny uvedené hodnoty představují potenciální odhadované úspory na základě zadaných vstupních údajů a oborových standardů. Skutečné výsledky se mohou v jednotlivých případech lišit a vždy závisí na specifických podmínkách implementace." },
    "industries": {
        "ecommerce": { "name": "E-commerce", "insight": "Integrací všech komunikačních kanálů do jedné platformy obvykle dosáhnete až {integration} provozních úspor. AI automatizace dokáže obvykle zpracovat až {ai} vašich zákaznických dotazů automaticky. Společně tato řešení obvykle přinášejí až {combined} celkového potenciálu úspor pro váš e-commerce." },
        "logistics": { "name": "Logistika & doprava", "insight": "Integrace kanálů obvykle poskytuje až {integration} snížení provozních nákladů díky sjednocenému sledování a komunikaci. AI automatizace obvykle zvládne až {ai} dotazů na zásilky a dodávky bez lidského zásahu. Společně obvykle můžete dosáhnout až {combined} celkového zlepšení provozní efektivity." },
        "finance": { "name": "Finanční služby & pojištění", "insight": "Integrace komunikačních kanálů obvykle ušetří až {integration} provozních nákladů při zachování bezpečnostních požadavků. AI dokáže obvykle automatizovat až {ai} dotazů na zůstatky, platby a produkty. Společně tato řešení obvykle přinášejí až {combined} celkových úspor pro finanční služby." },
        "manufacturing": { "name": "Výroba", "insight": "Integrace kanálů obvykle snižuje provozní náklady až o {integration} díky zefektivnění správy objednávek. AI automatizace obvykle zvládne až {ai} dotazů na dostupnost, specifikace a dodávky. Společná implementace obvykle dosahuje až {combined} celkového zlepšení provozní efektivity." },
        "travel": { "name": "Cestovní ruch & agentury", "insight": "Sjednocené komunikační kanály obvykle poskytují až {integration} úsporu nákladů a rychlejší zpracování rezervací. AI dokáže obvykle automatizovat až {ai} dotazů na rezervace a destinace. Společně obvykle můžete dosáhnout až {combined} celkového zlepšení v cestovních službách." },
        "telecom": { "name": "Telekomunikace & call centra", "insight": "Integrace kanálů obvykle přináší až {integration} provozních úspor se sjednoceným pohledem na zákazníky. AI automatizace obvykle zvládne až {ai} technických dotazů, aktivací a fakturace. Společná řešení obvykle poskytují až {combined} celkového potenciálu pro provozní excelenci." },
        "automotive": { "name": "Automotive", "insight": "Integrace komunikačních kanálů obvykle snižuje servisní náklady až o {integration} při zlepšení zákaznické zkušenosti. AI dokáže obvykle automatizovat až {ai} dotazů na díly, servis a informace o vozidlech. Společně tato řešení obvykle dosahují až {combined} celkového zlepšení provozní efektivity." },
        "it": { "name": "IT", "insight": "Integrace kanálů obvykle poskytuje až {integration} snížení provozních nákladů prostřednictvím sjednocených IT podpůrných platforem. AI automatizace dokáže obvykle zvládnout až {ai} technických podpůrných a systémových dotazů automaticky. Společně tato řešení obvykle poskytují až {combined} celkového potenciálu pro zlepšení IT provozní efektivity." },
        "energy": { "name": "Energetika", "insight": "Integrace komunikačních kanálů obvykle ušetří až {integration} provozních nákladů při zachování regulační shody. AI dokáže obvykle automatizovat až {ai} dotazů na fakturaci, spotřebu a služby. Společně tyto obvykle poskytují až {combined} celkových provozních úspor pro poskytovatele energie." },
        "healthcare": { "name": "Zdravotnictví", "insight": "Integrace kanálů obvykle poskytuje až {integration} snížení provozních nákladů při zajištění shody soukromí pacientů. AI automatizace dokáže obvykle zvládnout až {ai} dotazů na termíny, fakturaci a obecné zdravotní otázky. Kombinovaná řešení obvykle poskytují až {combined} celkového potenciálu pro zlepšení zdravotnických operací." },
        "other": { "name": "Ostatní", "insight": "Integrace kanálů obvykle poskytuje až {integration} snížení provozních nákladů napříč různými odvětvími. AI automatizace dokáže obvykle zpracovat až {ai} běžných zákaznických dotazů automaticky. Společně tato řešení obvykle přinášejí až {combined} celkového potenciálu pro zlepšení provozní efektivity." }
    },
    "caseStudies": {
        "ecommerce": { "company": "Košík", "url": "https://daktela.com/cs/customer-stories-with-quotes/kosik-cz" },
        "logistics": { "company": "DPD", "url": "https://daktela.com/cs/customer-stories-with-quotes/dpd-slovakia" },
        "finance": null, "manufacturing": null, "travel": null,
        "telecom": { "company": "Notino", "url": "https://daktela.com/cs/customer-stories-with-quotes/notino" },
        "automotive": { "company": "Gafa Auto", "url": "https://daktela.com/cs/customer-stories-with-quotes/gafa-auto" },
        "it": { "company": "Seznam", "url": "https://daktela.com/cs/customer-stories-with-quotes/seznam-cz" },
        "energy": null,
        "healthcare": { "company": "Nemocnice Bory", "url": "https://daktela.com/cs/customer-stories-with-quotes/nemocnice-bory" },
        "other": { "company": "Ticketportal", "url": "https://daktela.com/cs/customer-stories-with-quotes/ticketportal" }
    },
    "caseStudyText": { "prefix": "Podívejte se, jak", "suffix": "využívá Daktelu!" },
    "validation": { "channelsRequired": "Prosím, vyberte alespoň jeden komunikační kanál." },
    "chart": { "savingsLabel": "Roční úspora (Kč)", "hoursLabel": "Ušetřené hodiny ročně", "savingsAxis": "Úspora (Kč)", "hoursAxis": "Hodiny", "integrationLabel": "Sjednocení kanálů", "aiAutomationLabel": "AI automatizace", "potentialSavingsTitle": "Potenciální úspory podle segmentu - Sjednocení kanálů vs. AI", "percentageAxis": "Potenciální úspory (%)", "savingsBreakdownTitle": "Rozdělení potenciálních úspor", "integrationOnly": "Integrace\nkanálů", "aiOnly": "AI automatizace", "bothCombined": "Kombinované" },
    "leadModal": { "title": "Získejte svůj report", "subtitle": "Vyplňte prosím své údaje pro zobrazení výsledků úspor.", "firstName": "Jméno", "lastName": "Příjmení", "company": "Společnost", "email": "Pracovní e-mail", "submit": "Zobrazit výsledky", "sending": "Odesílání...", "validation": { "required": "Prosím, vyplňte všechna pole.", "email": "Zadejte prosím platnou e-mailovou adresu." } }
};

// Additional languages (PL, SR, HU, RO, SK) loaded dynamically from GitHub via loadExtraLanguages()

// 2. LOGIC CLASSES
class Translator {
    constructor() { this.currentLanguage = 'en'; }
    setLanguage(language) {
        if (window.translations && window.translations[language]) {
            this.currentLanguage = language;
            localStorage.setItem('preferred-language', language);
            this.translatePage();
            this.updateDynamicContent();
        }
    }
    translate(key, fallback = null) {
        const keys = key.split('.');
        let value = window.translations && window.translations[this.currentLanguage];
        for (const k of keys) {
            if (value && typeof value === 'object' && k in value) value = value[k];
            else {
                value = window.translations && window.translations['en'];
                for (const fallbackKey of keys) { if (value && typeof value === 'object') value = value[fallbackKey]; else { value = undefined; break; } }
                break;
            }
        }
        return typeof value === 'string' ? value : (fallback || key);
    }
    translatePage() {
        document.querySelectorAll('[data-translate]').forEach(element => {
            const key = element.getAttribute('data-translate');
            const translation = this.translate(key);
            if (element.tagName === 'INPUT' && (element.type === 'text' || element.type === 'email' || element.type === 'number')) {
                if (key.includes('Placeholder')) element.placeholder = translation;
            } else if (element.tagName === 'OPTION') element.textContent = translation;
            else element.textContent = translation;
        });
        document.querySelectorAll('[data-translate-title]').forEach(element => {
            const key = element.getAttribute('data-translate-title');
            element.title = this.translate(key);
        });
    }
    updateDynamicContent() { if (typeof updateSliderLabel === 'function') updateSliderLabel(); }
    getIndustryData(industryKey) {
        let lang = this.currentLanguage;
        if (window.translations[lang]?.industries?.[industryKey]) return window.translations[lang].industries[industryKey];
        return window.translations['en']?.industries?.[industryKey] || { name: industryKey, insight: 'No insight available' };
    }
    getCurrentLanguage() { return this.currentLanguage; }
    detectLanguageFromURL() {
        const supported = ['cs', 'sk', 'pl', 'sr', 'hu', 'ro'];
        const segments = window.location.pathname.split('/').filter(Boolean);
        if (segments.length === 0) return null;
        const first = segments[0].toLowerCase();
        return supported.includes(first) ? first : null;
    }
    initialize() {
        const lang = this.detectLanguageFromURL() || 'en';
        this.setLanguage(lang);
        document.getElementById('languageSelector').value = lang;
    }
}
const translator = new Translator();

// Industry Data
const industryData = {
    ecommerce: { name: "E-commerce", repeatQueries: 60, integrationSavings: 0.325, aiAutomationSavings: 0.55 },
    logistics: { name: "Logistics", repeatQueries: 50, integrationSavings: 0.30, aiAutomationSavings: 0.55 },
    finance: { name: "Finance", repeatQueries: 45, integrationSavings: 0.275, aiAutomationSavings: 0.45 },
    manufacturing: { name: "Manufacturing", repeatQueries: 40, integrationSavings: 0.10, aiAutomationSavings: 0.45 },
    travel: { name: "Travel", repeatQueries: 65, integrationSavings: 0.35, aiAutomationSavings: 0.55 },
    telecom: { name: "Telecom", repeatQueries: 70, integrationSavings: 0.30, aiAutomationSavings: 0.60 },
    automotive: { name: "Automotive", repeatQueries: 45, integrationSavings: 0.25, aiAutomationSavings: 0.55 },
    it: { name: "IT", repeatQueries: 60, integrationSavings: 0.30, aiAutomationSavings: 0.55 },
    energy: { name: "Energy", repeatQueries: 40, integrationSavings: 0.25, aiAutomationSavings: 0.45 },
    healthcare: { name: "Healthcare", repeatQueries: 35, integrationSavings: 0.20, aiAutomationSavings: 0.35 },
    other: { name: "Other", repeatQueries: 50, integrationSavings: 0.25, aiAutomationSavings: 0.50 }
};

const currencyConfig = {
    CZK: { symbol: 'Kč', defaultWage: 400, locale: 'cs-CZ' },
    EUR: { symbol: '€', defaultWage: 15, locale: 'de-DE' },
    GBP: { symbol: '£', defaultWage: 12, locale: 'en-GB' },
    HUF: { symbol: 'Ft', defaultWage: 4500, locale: 'hu-HU' },
    RON: { symbol: 'lei', defaultWage: 75, locale: 'ro-RO' },
    PLN: { symbol: 'zł', defaultWage: 60, locale: 'pl-PL' },
    RSD: { symbol: 'din', defaultWage: 1800, locale: 'sr-RS' }
};

let savingsChart = null;

// Make.com webhook URL - nahraď tímto placeholderem skutečnou webhook URL z Make.com
const MAKE_WEBHOOK_URL = 'https://hook.eu2.make.com/han25ef0tvgwusksg48jjx8tcfpk4jfk';
let _pendingCalcFormData = null;

// Dynamically load additional languages from GitHub
async function loadExtraLanguages() {
    try {
        const response = await fetch('https://raw.githubusercontent.com/filipmusildaktela/roiculator/main/translations-extra.json');
        if (response.ok) {
            const extraLanguages = await response.json();
            Object.assign(window.translations, extraLanguages);
        }
    } catch (error) {
        console.warn('Extra language packs loaded with fallback');
    }
    // Lead modal i18n - jediné místo pravdy pro všechny jazyky (přepíše případné duplicity z inline/GitHub)
    const leadModalI18n = {
        en: { title: "Get your personalized report", subtitle: "Enter your details to unlock your savings results.", firstName: "First name", lastName: "Last name", company: "Company", email: "Work email", submit: "Show my results", sending: "Sending...", validation: { required: "Please fill in all fields.", email: "Please enter a valid email address." } },
        cs: { title: "Získejte svůj report", subtitle: "Vyplňte prosím své údaje pro zobrazení výsledků úspor.", firstName: "Jméno", lastName: "Příjmení", company: "Společnost", email: "Pracovní e-mail", submit: "Zobrazit výsledky", sending: "Odesílání...", validation: { required: "Prosím, vyplňte všechna pole.", email: "Zadejte prosím platnou e-mailovou adresu." } },
        sk: { title: "Získajte svoj report", subtitle: "Vyplňte prosím svoje údaje pre zobrazenie výsledkov úspor.", firstName: "Meno", lastName: "Priezvisko", company: "Spoločnosť", email: "Pracovný e-mail", submit: "Zobraziť výsledky", sending: "Odosielanie...", validation: { required: "Prosím, vyplňte všetky polia.", email: "Zadajte prosím platnú e-mailovú adresu." } },
        pl: { title: "Otrzymaj spersonalizowany raport", subtitle: "Wprowadź swoje dane, aby zobaczyć wyniki oszczędności.", firstName: "Imię", lastName: "Nazwisko", company: "Firma", email: "Służbowy e-mail", submit: "Pokaż moje wyniki", sending: "Wysyłanie...", validation: { required: "Proszę wypełnić wszystkie pola.", email: "Proszę podać prawidłowy adres e-mail." } },
        hu: { title: "Kérje személyre szabott jelentését", subtitle: "Adja meg adatait a megtakarítási eredmények megtekintéséhez.", firstName: "Keresztnév", lastName: "Vezetéknév", company: "Cég", email: "Munkahelyi e-mail", submit: "Eredmények megjelenítése", sending: "Küldés...", validation: { required: "Kérjük, töltse ki az összes mezőt.", email: "Kérjük, adjon meg érvényes e-mail címet." } },
        ro: { title: "Obțineți raportul personalizat", subtitle: "Introduceți datele pentru a vizualiza rezultatele economiilor.", firstName: "Prenume", lastName: "Nume", company: "Companie", email: "E-mail de serviciu", submit: "Afișează rezultatele", sending: "Se trimite...", validation: { required: "Vă rugăm să completați toate câmpurile.", email: "Vă rugăm să introduceți o adresă de e-mail validă." } },
        sr: { title: "Preuzmite personalizovani izveštaj", subtitle: "Unesite svoje podatke da biste videli rezultate uštede.", firstName: "Ime", lastName: "Prezime", company: "Kompanija", email: "Poslovni e-mail", submit: "Prikaži rezultate", sending: "Slanje...", validation: { required: "Molimo popunite sva polja.", email: "Unesite važeću e-mail adresu." } }
    };
    Object.keys(leadModalI18n).forEach(lang => {
        if (!window.translations[lang]) window.translations[lang] = {};
        window.translations[lang].leadModal = leadModalI18n[lang];
    });
}

// Initialization
document.addEventListener('DOMContentLoaded', async function() {
    await loadExtraLanguages();
    translator.initialize();
    initializeForm();
    setupEventListeners();
});

function initializeForm() {
    document.getElementById('operators').value = 5;
    document.getElementById('avgTime').value = 8;

    const currentLanguage = translator.getCurrentLanguage();
    let defaultCurrency = 'GBP';
    if (currentLanguage === 'cs') defaultCurrency = 'CZK';
    else if (currentLanguage === 'sk') defaultCurrency = 'EUR';
    else if (currentLanguage === 'pl') defaultCurrency = 'PLN';
    else if (currentLanguage === 'sr') defaultCurrency = 'RSD';
    else if (currentLanguage === 'hu') defaultCurrency = 'HUF';
    else if (currentLanguage === 'ro') defaultCurrency = 'RON';

    document.getElementById('currency').value = defaultCurrency;
    document.getElementById('hourlyWage').value = currencyConfig[defaultCurrency].defaultWage;
    setupSlider();
}

function setupSlider() {
    const slider = document.getElementById('repeatQueries');
    const sliderValue = document.getElementById('repeatValue');
    slider.addEventListener('input', function() {
        if (sliderValue) sliderValue.textContent = this.value + '%';
        updateSliderLabel();
    });
}

function updateSliderLabel() {
    const slider = document.getElementById('repeatQueries');
    const label = document.querySelector('label[for="repeatQueries"]');
    if (label && slider) {
        const baseText = translator.translate('form.repeatQueries');
        label.innerHTML = `${baseText} <span id="repeatValue">${slider.value}%</span>`;
    }
}

function setupEventListeners() {
    document.getElementById('languageSelector').addEventListener('change', function() {
        translator.setLanguage(this.value);
        let defaultCurrency = 'GBP';
        if (this.value === 'cs') defaultCurrency = 'CZK';
        else if (this.value === 'sk') defaultCurrency = 'EUR';
        else if (this.value === 'pl') defaultCurrency = 'PLN';
        else if (this.value === 'sr') defaultCurrency = 'RSD';
        else if (this.value === 'hu') defaultCurrency = 'HUF';
        else if (this.value === 'ro') defaultCurrency = 'RON';
        document.getElementById('currency').value = defaultCurrency;
        document.getElementById('hourlyWage').value = currencyConfig[defaultCurrency].defaultWage;
    });

    document.getElementById('currency').addEventListener('change', function() {
        document.getElementById('hourlyWage').value = currencyConfig[this.value].defaultWage;
    });

    document.querySelectorAll('input[name="channels"]').forEach(cb => {
        cb.addEventListener('change', function() {
            const input = document.getElementById(this.value + '-count');
            const card = this.closest('.channel-card');
            input.disabled = !this.checked;
            if (this.checked) {
                card.classList.add('active');
                input.focus();
            } else {
                card.classList.remove('active');
                input.value = '';
            }
        });
    });

    document.getElementById('industry').addEventListener('change', function() {
        if (this.value && industryData[this.value]) {
            const val = industryData[this.value].repeatQueries;
            document.getElementById('repeatQueries').value = val;
            const sliderValue = document.getElementById('repeatValue');
            if(sliderValue) sliderValue.textContent = val + '%';
            updateSliderLabel();
        }
    });

    document.getElementById('roiForm').addEventListener('submit', function(e) {
        e.preventDefault();
        calculateROI();
    });

    document.getElementById('leadModalSubmit').addEventListener('click', submitLeadModal);
    document.getElementById('leadModalClose').addEventListener('click', closeLeadModal);
    document.getElementById('leadModalOverlay').addEventListener('click', function(e) {
        if (e.target === this) closeLeadModal();
    });
    ['leadFirstName', 'leadLastName', 'leadCompany', 'leadEmail'].forEach(id => {
        document.getElementById(id).addEventListener('keydown', function(e) {
            if (e.key === 'Enter') { e.preventDefault(); submitLeadModal(); }
        });
    });
    document.addEventListener('keydown', function(e) {
        if (e.key === 'Escape' && document.getElementById('leadModalOverlay').style.display !== 'none') {
            closeLeadModal();
        }
    });
}

function calculateROI() {
    const formData = getFormData();
    if (!validateForm(formData)) return;
    _pendingCalcFormData = formData;
    openLeadModal();
}

function runCalculationAndShow(formData) {
    document.querySelector('.form-section').classList.add('loading');
    setTimeout(() => {
        const results = performCalculations(formData);
        displayResults(results, formData);
        document.querySelector('.form-section').classList.remove('loading');
        const resultsSection = document.getElementById('resultsSection');
        resultsSection.style.display = 'block';
        if (window.innerWidth <= 768) {
            resultsSection.scrollIntoView({ behavior: 'smooth' });
        }
    }, 500);
}

function openLeadModal() {
    const overlay = document.getElementById('leadModalOverlay');
    document.getElementById('leadModalError').style.display = 'none';
    overlay.style.display = 'flex';
    document.body.style.overflow = 'hidden';
    setTimeout(() => document.getElementById('leadFirstName').focus(), 50);
}

function closeLeadModal() {
    document.getElementById('leadModalOverlay').style.display = 'none';
    document.body.style.overflow = '';
}

async function submitLeadModal() {
    const firstName = document.getElementById('leadFirstName').value.trim();
    const lastName = document.getElementById('leadLastName').value.trim();
    const company = document.getElementById('leadCompany').value.trim();
    const email = document.getElementById('leadEmail').value.trim();
    const errorEl = document.getElementById('leadModalError');
    errorEl.style.display = 'none';

    if (!firstName || !lastName || !company || !email) {
        errorEl.textContent = translator.translate('leadModal.validation.required');
        errorEl.style.display = 'block';
        return;
    }
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
        errorEl.textContent = translator.translate('leadModal.validation.email');
        errorEl.style.display = 'block';
        return;
    }

    const submitBtn = document.getElementById('leadModalSubmit');
    const originalText = submitBtn.textContent;
    submitBtn.disabled = true;
    submitBtn.textContent = translator.translate('leadModal.sending');

    const payload = {
        firstName, lastName, company, email,
        calculator: _pendingCalcFormData,
        language: translator.getCurrentLanguage(),
        timestamp: new Date().toISOString(),
        pageUrl: window.location.href
    };

    try {
        await fetch(MAKE_WEBHOOK_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });
    } catch (err) {
        console.warn('Lead webhook failed:', err);
    }

    submitBtn.disabled = false;
    submitBtn.textContent = originalText;

    const dataToUse = _pendingCalcFormData;
    _pendingCalcFormData = null;
    closeLeadModal();
    runCalculationAndShow(dataToUse);
}

function getFormData() {
    const channels = {};
    document.querySelectorAll('input[name="channels"]:checked').forEach(cb => {
        channels[cb.value] = parseInt(document.getElementById(cb.value + '-count').value) || 0;
    });
    return {
        operators: parseInt(document.getElementById('operators').value),
        channels: channels,
        avgTime: parseInt(document.getElementById('avgTime').value),
        hourlyWage: parseInt(document.getElementById('hourlyWage').value),
        currency: document.getElementById('currency').value,
        repeatQueries: parseInt(document.getElementById('repeatQueries').value),
        industry: document.getElementById('industry').value
    };
}

function validateForm(data) {
    if (Object.keys(data.channels).length === 0) {
        alert(translator.translate('validation.channelsRequired'));
        return false;
    }
    return true;
}

function performCalculations(data) {
    const industry = industryData[data.industry];
    let totalQueries = 0;
    Object.keys(data.channels).forEach(k => totalQueries += data.channels[k]);

    const automationRate = industry.aiAutomationSavings;
    const repeatingQueriesRate = data.repeatQueries / 100;
    const automateableQueries = totalQueries * repeatingQueriesRate;
    const automatedQueries = automateableQueries * automationRate;
    const timeSavedMinutes = automatedQueries * data.avgTime;
    const timeSavedHours = timeSavedMinutes / 60;
    const totalSavings = timeSavedHours * data.hourlyWage * 12;

    return { totalSavings, totalTimeSaved: timeSavedHours * 12, industry, totalQueries };
}

function generateDynamicInsight(template, i, a, c) {
    return template.replace(/\{integration\}/g, i + '%').replace(/\{ai\}/g, a + '%').replace(/\{combined\}/g, c + '%');
}

function formatCurrency(amount, currency) {
    const config = currencyConfig[currency];
    if (currency === 'HUF' || currency === 'RSD') {
        return new Intl.NumberFormat(config.locale, { minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(amount) + ' ' + config.symbol;
    }
    return new Intl.NumberFormat(config.locale, { style: 'currency', currency: currency, minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(amount);
}

function displayResults(results, formData) {
    document.getElementById('totalSavings').textContent = formatCurrency(results.totalSavings, formData.currency);

    const industryTranslated = translator.getIndustryData(formData.industry);
    const selInd = industryData[formData.industry];
    const intPct = Math.round(selInd.integrationSavings * 100);
    const aiPct = Math.round(selInd.aiAutomationSavings * 100);
    const comPct = Math.round((selInd.integrationSavings + selInd.aiAutomationSavings) * 100);

    let insight = industryTranslated?.insight || 'No insight';
    insight = generateDynamicInsight(insight, intPct, aiPct, comPct);
    insight = insight.replace(/(\d+%)/g, '<strong style="color: var(--dkt-red-orange);">$1</strong>');

    document.getElementById('industryInsight').innerHTML = `<h4>${translator.translate('industries.' + formData.industry + '.name')}</h4><p>${insight}</p>`;
    document.getElementById('channelBreakdown').style.display = 'none';
    displayCaseStudyBanner(formData.industry);
    createSavingsProgressChart(results, formData);
}

function displayCaseStudyBanner(industry) {
    const banner = document.getElementById('caseStudyBanner');
    const lang = translator.getCurrentLanguage();
    const data = window.translations[lang]?.caseStudies?.[industry];
    const text = window.translations[lang]?.caseStudyText;

    if (data && data.company) {
        banner.innerHTML = `<div class="case-study-text">${text.prefix} <strong>${data.company}</strong> ${text.suffix}</div>`;
        banner.onclick = () => window.open(data.url, '_blank', 'noopener');
        banner.style.display = 'block';
    } else {
        banner.style.display = 'none';
        banner.onclick = null;
    }
}

function createSavingsProgressChart(results, formData) {
    const ctx = document.getElementById('savingsChart').getContext('2d');
    if (savingsChart) savingsChart.destroy();

    const ind = industryData[formData.industry];
    const d1 = Math.round(ind.integrationSavings * 100);
    const d2 = Math.round(ind.aiAutomationSavings * 100);
    const d3 = Math.round((ind.integrationSavings + ind.aiAutomationSavings) * 100);

    const labels = [
        translator.translate('chart.integrationOnly').split('\n'),
        translator.translate('chart.aiOnly'),
        translator.translate('chart.bothCombined')
    ];

    savingsChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Potential Savings',
                data: [d1, d2, d3],
                backgroundColor: ['#FF5349', '#66CCFF', '#4CAF50'],
                borderColor: ['#e6473d', '#4db8ff', '#45a049'],
                borderWidth: 2,
                borderRadius: 8,
                barPercentage: 0.8
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { display: false },
                title: { display: true, text: translator.translate('chart.savingsBreakdownTitle'), color: '#003366', font: { size: 18, weight: 'bold' }, padding: 20 },
                tooltip: {
                    callbacks: {
                        label: function(context) {
                            const percentage = context.parsed.y + '%';
                            const currentLang = translator.currentLanguage;
                            if (currentLang === 'cs') return `až ${percentage} odhadovaných úspor`;
                            if (currentLang === 'pl') return `do ${percentage} szacunkowych oszczędności`;
                            return `up to ${percentage} estimated savings`;
                        }
                    }
                }
            },
            scales: {
                y: { beginAtZero: true, max: 100, ticks: { callback: v => v + '%' }, title: { display: true, text: translator.translate('chart.percentageAxis') } },
                x: { grid: { display: false } }
            }
        }
    });
}

function resetForm() {
    document.getElementById('roiForm').reset();
    initializeForm();
    document.querySelectorAll('[id$="-count"]').forEach(el => { el.disabled = true; el.value = ''; });
    document.querySelectorAll('.channel-card').forEach(el => el.classList.remove('active'));
    document.getElementById('resultsSection').style.display = 'none';
    if (savingsChart) { savingsChart.destroy(); savingsChart = null; }
    window.scrollTo({ top: 0, behavior: 'smooth' });
}

/* =========================================
   PDF GENERATOR (EXACT COPY OF LOGIC)
   ========================================= */

class PDFGenerator {
    constructor() { this.isGenerating = false; }

    async downloadPDF() {
        if (this.isGenerating) return;
        const downloadBtn = document.getElementById('downloadPdfBtn');
        this.isGenerating = true;
        downloadBtn.disabled = true;
        const originalContent = downloadBtn.innerHTML;
        downloadBtn.innerHTML = '⏳';

        try {
            const formData = getFormData();
            if (!this.validateFormData(formData)) throw new Error('Invalid form data');

            const pdfContainer = this.createPDFContainer();
            pdfContainer.innerHTML = await this.buildPDFContent(formData);
            document.body.appendChild(pdfContainer);

            const canvas = await html2canvas(pdfContainer, {
                scale: 2, useCORS: true, allowTaint: true, backgroundColor: '#ffffff',
                scrollX: 0, scrollY: 0, logging: false, imageTimeout: 15000, removeContainer: true
            });

            const { jsPDF } = window.jspdf;
            const pdf = new jsPDF('p', 'mm', 'a4');
            const imgData = canvas.toDataURL('image/png');
            const imgWidth = 210;
            const pageHeight = 297;
            const imgHeight = (canvas.height * imgWidth) / canvas.width;

            if (imgHeight <= pageHeight) {
                pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
            } else {
                let heightLeft = imgHeight;
                let position = 0;
                pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
                heightLeft -= pageHeight;
                while (heightLeft > 0) {
                    position = heightLeft - imgHeight;
                    pdf.addPage();
                    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
                    heightLeft -= pageHeight;
                }
            }

            const filename = `Daktela-ROI-Report-${new Date().toISOString().slice(0, 19).replace(/:/g, '-')}.pdf`;
            pdf.save(filename);
            document.body.removeChild(pdfContainer);

        } catch (error) {
            console.error('Error generating PDF:', error);
            alert('Error generating PDF. Please try again.');
        } finally {
            this.isGenerating = false;
            downloadBtn.disabled = false;
            downloadBtn.innerHTML = originalContent;
        }
    }

    validateFormData(formData) {
        if (!formData || !formData.operators || !formData.industry) return false;
        if (!formData.channels || Object.keys(formData.channels).length === 0) return false;
        return true;
    }

    createPDFContainer() {
        const container = document.createElement('div');
        container.className = 'pdf-content';
        // Note: Styles are also defined in CSS, but inline ensures html2canvas sees them
        container.style.cssText = `position: fixed; left: -9999px; top: 0; width: 794px; background: white; font-family: 'Inter', sans-serif; padding: 40px; box-sizing: border-box;`;
        return container;
    }

    async buildPDFContent(formData) {
        const currency = formData.currency;
        const industryDataTranslated = translator.getIndustryData(formData.industry);
        const selectedIndustryData = industryData[formData.industry];
        const results = performCalculations(formData);
        const activeChannels = Object.keys(formData.channels).filter(channel => formData.channels[channel] > 0);
        const header = await this.buildHeader();

        return `
            <div style="max-width: 714px; margin: 0 auto; font-family: 'Inter', sans-serif;">
                ${header}
                ${this.buildInputSummary(formData, currency, activeChannels)}
                ${this.buildResults(formData, results, currency, industryDataTranslated, selectedIndustryData)}
                ${this.buildFooter()}
            </div>
        `;
    }

    async loadLogoAsDataURL() {
        try {
            const response = await fetch('https://cdn.prod.website-files.com/66320cc6375bb0202a551c3c/66321058896abef316e28bb7_Daktela%20-LOGO-RGB-transparent-p-2000.png', { mode: 'cors' });
            const blob = await response.blob();
            return new Promise((resolve) => {
                const reader = new FileReader();
                reader.onload = () => resolve(reader.result);
                reader.readAsDataURL(blob);
            });
        } catch (error) { return null; }
    }

    async buildHeader() {
        const logoDataURL = await this.loadLogoAsDataURL();
        return `
            <div style="text-align: center; margin-bottom: 30px; border-bottom: 3px solid #FF5349; padding-bottom: 15px;">
                <div style="display: flex; align-items: center; justify-content: center; margin-bottom: 12px;">
                    ${logoDataURL ? `<img src="${logoDataURL}" style="height: 40px; margin-right: 15px;" />` : ''}
                    <h1 style="color: #003366; font-size: 26px; margin: 0; font-weight: 700;">${logoDataURL ? 'ROI-culator' : 'Daktela ROI-culator'}</h1>
                </div>
                <p style="color: #495057; font-size: 15px; margin: 0;">${translator.translate('header.subtitle')}</p>
            </div>
        `;
    }

    buildInputSummary(formData, currency, activeChannels) {
        return `
            <div style="margin-bottom: 30px;">
                <h2 style="color: #003366; font-size: 18px; margin-bottom: 15px; border-left: 4px solid #66CCFF; padding-left: 15px;">${translator.translate('pdf.inputParameters')}</h2>
                <div style="background: #f8f9fa; padding: 18px; border-radius: 12px; border: 1px solid #e2e8f0;">
                    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 12px;">
                        <div style="font-size: 14px;"><strong style="color: #003366;">${translator.translate('pdf.numberOfOperators')}:</strong><span style="color: #495057;"> ${formData.operators}</span></div>
                        <div style="font-size: 14px;"><strong style="color: #003366;">${translator.translate('pdf.averageResolutionTime')}:</strong><span style="color: #495057;"> ${formData.avgTime} ${translator.translate('pdf.minutes')}</span></div>
                    </div>
                    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 12px;">
                        <div style="font-size: 14px;"><strong style="color: #003366;">${translator.translate('pdf.hourlyWage')}:</strong><span style="color: #495057;"> ${formData.hourlyWage} ${currency}</span></div>
                        <div style="font-size: 14px;"><strong style="color: #003366;">${translator.translate('pdf.industry')}:</strong><span style="color: #495057;"> ${translator.translate('form.industry.' + formData.industry)}</span></div>
                    </div>
                    <div style="margin-bottom: 12px; font-size: 14px;"><strong style="color: #003366;">${translator.translate('pdf.repeatingQueriesRatio')}:</strong><span style="color: #495057;"> ${formData.repeatQueries}%</span></div>
                    <div style="font-size: 14px;"><strong style="color: #003366;">${translator.translate('pdf.activeChannels')}:</strong>
                        <div style="margin-top: 8px;">
                            ${activeChannels.map(channel => `<div style="display: inline-block; background: #66CCFF; color: white; padding: 4px 10px; border-radius: 16px; margin: 2px 4px 2px 0; font-size: 13px;">${translator.translate('form.channels.' + channel)}: ${formData.channels[channel].toLocaleString()}</div>`).join('')}
                        </div>
                    </div>
                </div>
            </div>
        `;
    }

    buildResults(formData, results, currency, industryDataTranslated, selectedIndustryData) {
        return `
            <div style="margin-bottom: 30px;">
                <h2 style="color: #003366; font-size: 18px; margin-bottom: 15px; border-left: 4px solid #FF5349; padding-left: 15px;">${translator.translate('results.title')}</h2>
                <div style="text-align: center; background: linear-gradient(135deg, #FF5349, #e6473d); color: white; padding: 30px; border-radius: 20px; margin-bottom: 25px; box-shadow: 0 8px 32px rgba(255, 83, 73, 0.2);">
                    <div style="font-size: 32px; font-weight: 800; margin-bottom: 8px;">${formatCurrency(results.totalSavings, currency)}</div>
                    <div style="font-size: 16px; opacity: 0.9;">${translator.translate('results.totalSavings')}</div>
                </div>
                <div style="background: linear-gradient(135deg, rgba(102, 0, 255, 0.05), rgba(102, 204, 255, 0.05)); padding: 20px; border-radius: 15px; border-left: 4px solid #6600FF; margin-bottom: 25px;">
                    <h3 style="color: #003366; margin: 0 0 12px 0; font-size: 16px;">${translator.translate('industries.' + formData.industry + '.name')}</h3>
                    <p style="color: #495057; line-height: 1.5; margin: 0; font-size: 13px;">${generateDynamicInsight(industryDataTranslated?.insight || 'Industry-specific insights help optimize your savings potential.', Math.round(selectedIndustryData.integrationSavings * 100), Math.round(selectedIndustryData.aiAutomationSavings * 100), Math.round((selectedIndustryData.integrationSavings + selectedIndustryData.aiAutomationSavings) * 100))}</p>
                </div>
                ${this.buildSavingsBreakdown(selectedIndustryData)}
            </div>
        `;
    }

    buildSavingsBreakdown(selectedIndustryData) {
        return `
            <div style="background: #f8f9fa; padding: 20px; border-radius: 15px; text-align: center; border: 1px solid #e2e8f0;">
                <h3 style="color: #003366; margin: 0 0 15px 0; font-size: 16px;">${translator.translate('chart.savingsBreakdownTitle')}</h3>
                <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin-top: 15px;">
                    <div style="text-align: center;">
                        <div style="background: #FF5349; color: white; padding: 12px; border-radius: 10px; margin-bottom: 8px;"><div style="font-size: 22px; font-weight: bold;">${Math.round(selectedIndustryData.integrationSavings * 100)}%</div></div>
                        <div style="font-size: 11px; color: #495057; font-weight: 600; line-height: 1.3;">${translator.translate('chart.integrationOnly').replace('\\n', ' ')}</div>
                    </div>
                    <div style="text-align: center;">
                        <div style="background: #66CCFF; color: white; padding: 12px; border-radius: 10px; margin-bottom: 8px;"><div style="font-size: 22px; font-weight: bold;">${Math.round(selectedIndustryData.aiAutomationSavings * 100)}%</div></div>
                        <div style="font-size: 11px; color: #495057; font-weight: 600; line-height: 1.3;">${translator.translate('chart.aiOnly')}</div>
                    </div>
                    <div style="text-align: center;">
                        <div style="background: #4CAF50; color: white; padding: 12px; border-radius: 10px; margin-bottom: 8px;"><div style="font-size: 22px; font-weight: bold;">${Math.round((selectedIndustryData.integrationSavings + selectedIndustryData.aiAutomationSavings) * 100)}%</div></div>
                        <div style="font-size: 11px; color: #495057; font-weight: 600; line-height: 1.3;">${translator.translate('chart.bothCombined')}</div>
                    </div>
                </div>
            </div>
        `;
    }

    buildFooter() {
        return `
            <div style="padding-top: 15px; border-top: 1px solid #e2e8f0;">
                <div style="background: #f8f9fa; padding: 12px; border-radius: 8px; border-left: 3px solid #FF5349;">
                    <p style="margin: 0; font-size: 9px; color: #6c757d; line-height: 1.4; font-style: italic;">${translator.translate('pdf.disclaimer')}</p>
                </div>
            </div>
        `;
    }
}

const pdfGenerator = new PDFGenerator();
function downloadPDF() { pdfGenerator.downloadPDF(); }
